import{uid,read,write,escapeHtml,formatDate,toast,pages,bindMobile,download}from'../assets/shared.js';
const KEY='wdev_fluxo_pro_v1',PER_PAGE=5;
const seed=[
{id:uid(),title:'Mapear jornada de cadastro',project:'Portal Cliente',owner:'Ana Lima',status:'Concluída',priority:'Alta',due:'2026-10-02',progress:100},
{id:uid(),title:'Criar componentes do dashboard',project:'Portal Cliente',owner:'William Barbosa',status:'Em andamento',priority:'Alta',due:'2026-10-10',progress:68},
{id:uid(),title:'Revisar acessibilidade do formulário',project:'Portal Cliente',owner:'Marina Costa',status:'Planejada',priority:'Média',due:'2026-10-14',progress:10},
{id:uid(),title:'Integrar consulta de pedidos',project:'Área do Parceiro',owner:'William Barbosa',status:'Em andamento',priority:'Alta',due:'2026-10-08',progress:42},
{id:uid(),title:'Documentar tokens visuais',project:'Design System',owner:'Ana Lima',status:'Concluída',priority:'Baixa',due:'2026-09-30',progress:100},
{id:uid(),title:'Validar tabela em dispositivos móveis',project:'Área do Parceiro',owner:'Marina Costa',status:'Planejada',priority:'Média',due:'2026-10-18',progress:0},
{id:uid(),title:'Otimizar carregamento inicial',project:'Portal Cliente',owner:'William Barbosa',status:'Em andamento',priority:'Média',due:'2026-10-12',progress:74},
{id:uid(),title:'Criar estados de erro da API',project:'Área do Parceiro',owner:'Ana Lima',status:'Planejada',priority:'Alta',due:'2026-10-16',progress:15}
];
let items=read(KEY,seed),page=1,editing=null;
const $=s=>document.querySelector(s),rows=$('#rows'),dialog=$('#taskDialog');
function filtered(){const q=$('#search').value.toLowerCase(),s=$('#statusFilter').value,p=$('#priorityFilter').value;return items.filter(x=>(!q||`${x.title} ${x.project} ${x.owner}`.toLowerCase().includes(q))&&(!s||x.status===s)&&(!p||x.priority===p))}
function statusBadge(v){return v==='Concluída'?'ok':v==='Em andamento'?'warn':''}
function priorityBadge(v){return v==='Alta'?'danger':v==='Média'?'warn':'ok'}
function render(){const data=filtered(),totalPages=Math.max(1,Math.ceil(data.length/PER_PAGE));page=Math.min(page,totalPages);const view=data.slice((page-1)*PER_PAGE,page*PER_PAGE);rows.innerHTML=view.map(x=>`<tr><td><strong>${escapeHtml(x.title)}</strong><div class="meta">${escapeHtml(x.project)}</div></td><td>${escapeHtml(x.owner)}</td><td><span class="badge ${statusBadge(x.status)}">${x.status}</span></td><td><span class="badge ${priorityBadge(x.priority)}">${x.priority}</span></td><td>${formatDate(x.due)}</td><td><div class="progress" aria-label="${x.progress}%"><span style="width:${x.progress}%"></span></div><div class="meta">${x.progress}%</div></td><td><div class="row-actions"><button class="btn small" data-edit="${x.id}">Editar</button><button class="btn small danger" data-delete="${x.id}">Excluir</button></div></td></tr>`).join('');$('#empty').hidden=view.length>0;$('#pageInfo').textContent=`${data.length} tarefa(s) · página ${page} de ${totalPages}`;$('#pageButtons').innerHTML=pages(totalPages,page);$('#mTotal').textContent=items.length;$('#mDoing').textContent=items.filter(x=>x.status==='Em andamento').length;$('#mDone').textContent=items.filter(x=>x.status==='Concluída').length;const today=new Date().toISOString().slice(0,10);$('#mLate').textContent=items.filter(x=>x.status!=='Concluída'&&x.due<today).length}
function openForm(item){editing=item?.id||null;$('#dialogTitle').textContent=item?'Editar tarefa':'Nova tarefa';$('#taskId').value=item?.id||'';$('#title').value=item?.title||'';$('#project').value=item?.project||'';$('#owner').value=item?.owner||'';$('#status').value=item?.status||'Planejada';$('#priority').value=item?.priority||'Média';$('#due').value=item?.due||new Date().toISOString().slice(0,10);$('#progress').value=item?.progress??0;dialog.showModal();$('#title').focus()}
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const data={id:editing||uid(),title:$('#title').value.trim(),project:$('#project').value.trim(),owner:$('#owner').value.trim(),status:$('#status').value,priority:$('#priority').value,due:$('#due').value,progress:Math.max(0,Math.min(100,Number($('#progress').value)))};items=editing?items.map(x=>x.id===editing?data:x):[data,...items];write(KEY,items);dialog.close();toast(editing?'Tarefa atualizada.':'Tarefa criada.');render()});
rows.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openForm(items.find(x=>x.id===edit.dataset.edit));if(del&&confirm('Excluir esta tarefa?')){items=items.filter(x=>x.id!==del.dataset.delete);write(KEY,items);toast('Tarefa excluída.');render()}});
$('#pageButtons').addEventListener('click',e=>{if(e.target.dataset.page){page=Number(e.target.dataset.page);render()}});['search','statusFilter','priorityFilter'].forEach(id=>$('#'+id).addEventListener('input',()=>{page=1;render()}));$('#newBtn').addEventListener('click',()=>openForm());document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>dialog.close()));$('#exportBtn').addEventListener('click',()=>download('fluxo-pro-tarefas.json',JSON.stringify(items,null,2)));bindMobile();render();
