import{uid,read,write,escapeHtml,money,toast,pages,bindMobile,download}from'../assets/shared.js';
const KEY='wdev_estoque_360_v1',PER_PAGE=6;
const seed=[
{id:uid(),name:'Teclado mecânico Atlas',sku:'TEC-AT-001',category:'Periféricos',quantity:18,minimum:8,cost:189.9,supplier:'Norte Tech'},
{id:uid(),name:'Mouse sem fio Move',sku:'MOU-MV-014',category:'Periféricos',quantity:6,minimum:10,cost:74.5,supplier:'Norte Tech'},
{id:uid(),name:'Monitor 24” ProView',sku:'MON-PV-024',category:'Monitores',quantity:9,minimum:5,cost:769,supplier:'Visual Parts'},
{id:uid(),name:'Hub USB-C 7 portas',sku:'HUB-US-007',category:'Acessórios',quantity:4,minimum:7,cost:119.9,supplier:'Connect Brasil'},
{id:uid(),name:'Suporte articulado Duo',sku:'SUP-DU-002',category:'Ergonomia',quantity:12,minimum:6,cost:224.8,supplier:'Office Line'},
{id:uid(),name:'Webcam Full HD Focus',sku:'WEB-FC-108',category:'Vídeo',quantity:3,minimum:6,cost:156,supplier:'Visual Parts'},
{id:uid(),name:'Headset ClearTalk',sku:'HEA-CT-020',category:'Áudio',quantity:15,minimum:8,cost:132.4,supplier:'Connect Brasil'},
{id:uid(),name:'Cabo USB-C 2m',sku:'CAB-US-200',category:'Acessórios',quantity:42,minimum:20,cost:24.9,supplier:'Connect Brasil'}
];
let items=read(KEY,seed),page=1,editing=null;const $=s=>document.querySelector(s),rows=$('#rows'),dialog=$('#productDialog');
function filtered(){const q=$('#search').value.toLowerCase(),c=$('#categoryFilter').value,s=$('#stockFilter').value;return items.filter(x=>(!q||`${x.name} ${x.sku} ${x.supplier}`.toLowerCase().includes(q))&&(!c||x.category===c)&&(!s||(s==='low'?x.quantity<=x.minimum:x.quantity>x.minimum)))}
function categories(){const current=$('#categoryFilter').value;$('#categoryFilter').innerHTML='<option value="">Todas as categorias</option>'+[...new Set(items.map(x=>x.category))].sort().map(c=>`<option>${escapeHtml(c)}</option>`).join('');$('#categoryFilter').value=current}
function render(){categories();const data=filtered(),totalPages=Math.max(1,Math.ceil(data.length/PER_PAGE));page=Math.min(page,totalPages);const view=data.slice((page-1)*PER_PAGE,page*PER_PAGE);rows.innerHTML=view.map(x=>{const low=x.quantity<=x.minimum;return`<tr><td><strong>${escapeHtml(x.name)}</strong><div class="meta">${escapeHtml(x.sku)}</div></td><td><span class="badge">${escapeHtml(x.category)}</span></td><td><span class="badge ${low?'danger':'ok'}">${x.quantity} un.</span></td><td>${x.minimum} un.</td><td>${money(x.cost)}</td><td>${escapeHtml(x.supplier)}</td><td><div class="row-actions"><button class="btn small" data-edit="${x.id}">Editar</button><button class="btn small danger" data-delete="${x.id}">Excluir</button></div></td></tr>`}).join('');$('#empty').hidden=view.length>0;$('#pageInfo').textContent=`${data.length} produto(s) · página ${page} de ${totalPages}`;$('#pageButtons').innerHTML=pages(totalPages,page);$('#mProducts').textContent=items.length;$('#mUnits').textContent=items.reduce((a,x)=>a+x.quantity,0);$('#mValue').textContent=money(items.reduce((a,x)=>a+x.quantity*x.cost,0));$('#mLow').textContent=items.filter(x=>x.quantity<=x.minimum).length}
function openForm(item){editing=item?.id||null;$('#dialogTitle').textContent=item?'Editar produto':'Novo produto';['name','sku','category','quantity','minimum','cost','supplier'].forEach(k=>$('#'+k).value=item?.[k]??'');dialog.showModal();$('#name').focus()}
$('#productForm').addEventListener('submit',e=>{e.preventDefault();const data={id:editing||uid(),name:$('#name').value.trim(),sku:$('#sku').value.trim().toUpperCase(),category:$('#category').value.trim(),quantity:Number($('#quantity').value),minimum:Number($('#minimum').value),cost:Number($('#cost').value),supplier:$('#supplier').value.trim()};items=editing?items.map(x=>x.id===editing?data:x):[data,...items];write(KEY,items);dialog.close();toast(editing?'Produto atualizado.':'Produto criado.');render()});
rows.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openForm(items.find(x=>x.id===edit.dataset.edit));if(del&&confirm('Excluir este produto?')){items=items.filter(x=>x.id!==del.dataset.delete);write(KEY,items);toast('Produto excluído.');render()}});$('#pageButtons').addEventListener('click',e=>{if(e.target.dataset.page){page=Number(e.target.dataset.page);render()}});['search','categoryFilter','stockFilter'].forEach(id=>$('#'+id).addEventListener('input',()=>{page=1;render()}));$('#newBtn').addEventListener('click',()=>openForm());document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>dialog.close()));$('#exportBtn').addEventListener('click',()=>{const head='Produto,SKU,Categoria,Quantidade,Mínimo,Custo,Fornecedor\n';const body=items.map(x=>[x.name,x.sku,x.category,x.quantity,x.minimum,x.cost,x.supplier].map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');download('estoque-360.csv','\ufeff'+head+body,'text/csv;charset=utf-8')});bindMobile();render();
