import{uid,read,write,escapeHtml,formatDate,money,toast,pages,bindMobile}from'../assets/shared.js';
const KEY='wdev_agenda_pro_v1',PER_PAGE=5;const day=(offset)=>{const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)};
const seed=[
{id:uid(),client:'Camila Rodrigues',service:'Consultoria de imagem',professional:'Marina Costa',date:day(0),time:'09:00',status:'Confirmado',price:180,notes:'Primeiro atendimento'},
{id:uid(),client:'Rafael Oliveira',service:'Sessão estratégica',professional:'William Barbosa',date:day(0),time:'11:30',status:'Solicitado',price:240,notes:''},
{id:uid(),client:'Júlia Mendes',service:'Avaliação completa',professional:'Ana Lima',date:day(1),time:'10:00',status:'Confirmado',price:150,notes:'Enviar material após a sessão'},
{id:uid(),client:'Bruno Martins',service:'Acompanhamento mensal',professional:'William Barbosa',date:day(2),time:'14:30',status:'Confirmado',price:320,notes:''},
{id:uid(),client:'Larissa Souza',service:'Consultoria de imagem',professional:'Marina Costa',date:day(-1),time:'16:00',status:'Concluído',price:180,notes:''},
{id:uid(),client:'Paulo Nunes',service:'Sessão estratégica',professional:'Ana Lima',date:day(3),time:'13:00',status:'Cancelado',price:240,notes:'Cliente solicitou remarcação'},
{id:uid(),client:'Fernanda Alves',service:'Avaliação completa',professional:'Marina Costa',date:day(4),time:'08:30',status:'Solicitado',price:150,notes:''}
];
let items=read(KEY,seed),page=1,editing=null;const $=s=>document.querySelector(s),rows=$('#rows'),dialog=$('#bookingDialog');
function filtered(){const q=$('#search').value.toLowerCase(),d=$('#dateFilter').value,s=$('#statusFilter').value;return items.filter(x=>(!q||`${x.client} ${x.service} ${x.professional}`.toLowerCase().includes(q))&&(!d||x.date===d)&&(!s||x.status===s)).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`))}
function statusClass(v){return v==='Concluído'?'ok':v==='Confirmado'?'warn':v==='Cancelado'?'danger':''}
function render(){const data=filtered(),totalPages=Math.max(1,Math.ceil(data.length/PER_PAGE));page=Math.min(page,totalPages);const view=data.slice((page-1)*PER_PAGE,page*PER_PAGE);rows.innerHTML=view.map(x=>`<tr><td><strong>${formatDate(x.date)}</strong><div class="meta">${x.time}</div></td><td><strong>${escapeHtml(x.client)}</strong>${x.notes?`<div class="meta">${escapeHtml(x.notes)}</div>`:''}</td><td>${escapeHtml(x.service)}</td><td>${escapeHtml(x.professional)}</td><td><span class="badge ${statusClass(x.status)}">${x.status}</span></td><td>${money(x.price)}</td><td><div class="row-actions"><button class="btn small" data-edit="${x.id}">Editar</button><button class="btn small danger" data-delete="${x.id}">Excluir</button></div></td></tr>`).join('');$('#empty').hidden=view.length>0;$('#pageInfo').textContent=`${data.length} agendamento(s) · página ${page} de ${totalPages}`;$('#pageButtons').innerHTML=pages(totalPages,page);$('#mTotal').textContent=items.length;$('#mConfirmed').textContent=items.filter(x=>x.status==='Confirmado').length;$('#mDone').textContent=items.filter(x=>x.status==='Concluído').length;$('#mRevenue').textContent=money(items.filter(x=>x.status!=='Cancelado').reduce((a,x)=>a+x.price,0))}
function openForm(item){editing=item?.id||null;$('#dialogTitle').textContent=item?'Editar agendamento':'Novo agendamento';['client','service','professional','date','time','status','price','notes'].forEach(k=>{$('#'+k).value=item?.[k]??(k==='date'?day(0):k==='status'?'Solicitado':'')});dialog.showModal();$('#client').focus()}
$('#bookingForm').addEventListener('submit',e=>{e.preventDefault();const data={id:editing||uid(),client:$('#client').value.trim(),service:$('#service').value.trim(),professional:$('#professional').value.trim(),date:$('#date').value,time:$('#time').value,status:$('#status').value,price:Number($('#price').value),notes:$('#notes').value.trim()};items=editing?items.map(x=>x.id===editing?data:x):[data,...items];write(KEY,items);dialog.close();toast(editing?'Agendamento atualizado.':'Agendamento criado.');render()});
rows.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openForm(items.find(x=>x.id===edit.dataset.edit));if(del&&confirm('Excluir este agendamento?')){items=items.filter(x=>x.id!==del.dataset.delete);write(KEY,items);toast('Agendamento excluído.');render()}});$('#pageButtons').addEventListener('click',e=>{if(e.target.dataset.page){page=Number(e.target.dataset.page);render()}});['search','dateFilter','statusFilter'].forEach(id=>$('#'+id).addEventListener('input',()=>{page=1;render()}));$('#todayBtn').addEventListener('click',()=>{$('#dateFilter').value=day(0);page=1;render()});$('#clearBtn').addEventListener('click',()=>{$('#search').value='';$('#dateFilter').value='';$('#statusFilter').value='';page=1;render()});$('#newBtn').addEventListener('click',()=>openForm());document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>dialog.close()));bindMobile();render();
